name: Bug report
description: Create a report to help us improve
type: bug
body:

  - type: markdown
    attributes:
      value: |
        Avogadro version: (please complete the following information from the About box)
  - type: input
    attributes:
      label: Avogadrolibs
      placeholder: 1.103.0-26-g8bf0cbad682e
      validations:
        required: true
  - type: input
    attributes:
      label: Qt
      placeholder: 6.8.3
      validations:
        required: true

  - type: markdown
    attributes:
      value: |
        Desktop version: (please complete the following information)

  - type: input
    attributes:
      label: OS
      placeholder: MacOS 10.12.4
      validations:
        required: true
  - type: input
    attributes:
      label: Compiler (if you built from source)
      placeholder: GCC 14

  - type: input
    attributes:
      label: Problem
      description: |
        Describe the bug
        A clear and concise description of what the bug is.
      validations:
        required: true

  - type: input
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      validations:
        required: true

  - type: input
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      validations:
        required: true

  - type: input
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    attributes:
      label: Additional context
      description: Add any other context about the problem here. **Please consider uploading or linking test files.**
